### ISSUE TITLE
External Network type for LabNet

### ISSUE THREAD

**Issue by g0t4** [theJasonHelmick/PS-AutoLab-Env#33]
If I change the type of network to External, when it's created, the Setup-Lab script fails to download the ISO, because the host networking is temporarily lost. I'm not sure if this happens with Internal network type. Just a heads up, might want to delay a bit and/or poll for network connectivity, or maybe warn users to run the script again.

**Comment by theJasonHelmick** [comment]
Leaving this for comment -- is external for an isolated lab important?  Please respond.

**Comment by g0t4** [comment]
I like to use it so I can connect to my hosts easily from any machine on my home network.  Also, it can simplify labs if we don't need NAT, which right now is a hassle with the single NAT network limitation.

**Comment by g0t4** [comment]
Feel free to close this issue too, just wanted to leave an FYI in case others have trouble.

**Comment by theJasonHelmick** [comment]
Well, first -- you can define the switch in the PSD1 as external -- though I haven't fully tested.  So if your testing it and its working, we can make sure to add to documentation so that others are aware of it.  You can also define multiple switches -- and I believe multiple Nats on those switches, however, again I need to fully test this.  The Nat thing is a Windows issue -- so nothing I can do about that if it doesn't work -- but I think we can accomplish more complicated goals.

**Comment by g0t4** [comment]
Yeah I've tested External, it works ok minus the issue above but I can just run Setup-Lab again a second time and things are fine.
