### ISSUE TITLE
Design Suggestion

### ISSUE THREAD

**Issue by jdhitsolutions** [theJasonHelmick/PS-AutoLab-Env#52]
I've been thinking about the overall design of this project and there appears to be a lot of duplication. In each of the different configurations, are the scripts like Run-Lab identical? If so, I'd suggest creating a folder like Library or Tools and centralize the scripts. Perhaps even better would  be to turn the scripts into functions and create a module. The functions could have a Path parameter that defaults to the current location. The end result is that you can still run the commands from each configuration directory but overall management of the code base could be simplified.  Thoughts?

**Comment by theJasonHelmick** [comment]
Totally agree!  Originally, the control scripts were unique to the configurations. As it stands today, they are not -- they are the same across configs and I would love to do this.  Do you have any ideas on how you think it best to proceed?  And if so, this would greatly improve maintenance for me -- as I've screwed up a few commits already.  Question is, since this would be a breaking change from the current design -- it would be another major point release.  Is this something we might be able to do in this release?  The only Dev work in progress on this release is @majst32 finishing ADCS in the POC-MultiRole config --- so the system is static enough to work on at the moment. @jdhitsolutions

**Comment by theJasonHelmick** [comment]
@jdhitsolutions @majst32 - so - philosophical question -- Jeff, whats the community feeling of having control scripts turned into function in a module --- in other words -- All the test formatting, write-host and colorization......that pretty much all violates best practice and triggers everything in the script analyzer --- I think the module is a great approach, just trying to justify the approach.
Or is that stupid.  Anyway -- will put together a test module

**Comment by jdhitsolutions** [comment]
I see this project as something that can eventually be modular easy to re-use. I don't see an issue with the control scripts as functions. They can be parameterized to make them easy to re-use.  Someday I'd love for an author or trainer to be able to easily generate a configuration. For example, I can foresee helper functions to export user information to a json file for example. 

Of course, if you think what you have now is all you ever intend to do, then don't bother and call it a day.

**Comment by theJasonHelmick** [comment]
ok -- almost done -- let me master this in the Dev-Modules branch -- I will let you know and you can test ...and clean my crappy module ;)

**Comment by theJasonHelmick** [comment]
@jdhitsolutions @majst32  Jeff -- After I send this to master today - I will ping you --- it would be great if you could add the helper function to export AD users groups and OU's --- no rush -- it can be added as a point release later -- but I'm leaving this open for further discussion and issue reference.

**Comment by theJasonHelmick** [comment]
This was resolved in a later release. Closing issue
